- name: Deploy app
  hosts: all
  vars_files:
    - config.yml
    - vault.yml
  pre_tasks:
    - name: Create .env content from vars
      set_fact:
        env_lines: |
          {% for key, value in vars.items() if key not in ['ansible_facts', 'inventory_hostname', 'group_names', 'groups', 'hostvars', 'play_hosts', 'ansible_playbook_python', 'playbook_dir', 'role_names'] and value is string %}
          {{ key | upper }}={{ value }}
          {% endfor %}

    - name: Create env file on remote (temporary)
      ansible.builtin.copy:
        dest: /tmp/myapp.env
        content: "{{ env_lines }}"
        mode: "0600"
      no_log: true

  post_tasks:
    - name: Remove env file after startup
      ansible.builtin.file:
        path: /tmp/myapp.env
        state: absent
      no_log: true

  roles:
    - { role: infra, tags: ["infra"] }
    - { role: mailforwarder, tags: ["mailforwarder"] }
    - { role: troopconnect, tags: ["troopconnect"] }
