- name: Deploy app
  hosts: target_servers
  vars_files:
    - config.yml # non-sensitive
    - vault.yml # sensitive (vault-encrypted)

  tasks:
    - name: Create env file on remote (temporary)
      copy:
        dest: /tmp/myapp.env
        content: |
          DB_HOST=localhost
          DB_USER={{ db_user }}
          DB_PASSWORD={{ db_password }}
        mode: "0600"
      no_log: true

    - name: Start docker-compose
      community.docker.docker_compose_v2:
        project_src: /path/to/docker-compose-directory
        env_files:
          - /tmp/myapp.env

    # - name: Remove env file after startup
    #   file:
    #     path: /tmp/myapp.env
    #     state: absent
