services:
  mail-forward:
    image: zixia/simple-mail-forwarder
    env_file: "/tmp/myapp.env"
    environment:
      - SMF_POSTFIXMAIN_sender_canonical_maps=tcp:localhost:10001
      - SMF_POSTFIXMAIN_sender_canonical_classes=envelope_sender
      - SMF_POSTFIXMAIN_recipient_canonical_maps=tcp:localhost:10002
      - SMF_POSTFIXMAIN_recipient_canonical_classes=envelope_recipient,header_recipient=value
    volumes:
      - dkim:/var/db/dkim
      - /etc/letsencrypt/live/${MAILSERVER}:/etc/postfix/cert
    ports:
      - "25:25"
      - "587:587"

volumes:
  dkim:
