services:
  caddy:
    env_file: "/tmp/myapp.env"
    build:
      context: caddy
      args:
        - LETSENCRYPT_CONTACT_EMAIL=${LETSENCRYPT_CONTACT_EMAIL}
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - "${PROJECT_DIR}/static:/vol/static"
      - "${PROJECT_DIR}/media:/vol/media"
    networks:
      - shared_net

networks:
  shared_net:
    external: true

volumes:
  caddy_data:
  caddy_config:
