services:
  mail-forward:
    image: zixia/simple-mail-forwarder
    env_file: "/tmp/myapp.env"
    volumes:
      - dkim:/var/db/dkim
      - /etc/letsencrypt/live/${MAILSERVER}:/etc/postfix/cert
    ports:
      - "25:25"
      - "587:587"

volumes:
  dkim:
