services:
  caddy:
    env_file: "/tmp/myapp.env"
    build:
      context: caddy
      args:
        - LETSENCRYPT_CONTACT_EMAIL=${LETSENCRYPT_CONTACT_EMAIL}
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - "${PROJECT_DIR}/app/static:/vol/static"
      - "${PROJECT_DIR}/app/media:/vol/media"
    networks:
      - shared_net
    depends_on:
      - troopconnect

  postgres:
    image: postgres:alpine
    restart: always
    env_file: "/tmp/myapp.env"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=troopconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_net

  redis:
    image: redis:alpine
    restart: always
    networks:
      - shared_net

  troopconnect:
    build:
      context: .
      dockerfile: app/Dockerfile.prod
    restart: always
    env_file: "/tmp/myapp.env"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn troopconnect.wsgi:application --bind 0.0.0.0:9000 --workers 4 --timeout 120"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/troopconnect
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=troopconnect.settings
    volumes:
      - "${PROJECT_DIR}/app/static:/app/static"
      - "${PROJECT_DIR}/app/media:/app/media"
    networks:
      - shared_net
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
      dockerfile: app/Dockerfile.prod
    restart: always
    env_file: "/tmp/myapp.env"
    command: celery -A troopconnect worker -l INFO
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/troopconnect
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=troopconnect.settings
    networks:
      - shared_net
    depends_on:
      - postgres
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: app/Dockerfile.prod
    restart: always
    env_file: "/tmp/myapp.env"
    command: celery -A troopconnect beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/troopconnect
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=troopconnect.settings
    networks:
      - shared_net
    depends_on:
      - postgres
      - redis

networks:
  shared_net:
    external: true

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
