# Generated by Django 6.0.3 on 2026-08-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0019_email_template_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('documents', models.FileField(upload_to='attestations/')),
                ('signature', models.FileField(upload_to='attestations/')),
                ('split_mode', models.CharField(choices=[('one_page', 'One page per document'), ('marker', 'New document on a marker page')], default='one_page', max_length=10)),
                ('split_marker', models.CharField(blank=True, help_text='With marker mode, a new document starts on a page whose text begins with this marker (e.g. "Aux parents de").', max_length=200)),
                ('name_anchor', models.JSONField(blank=True, null=True)),
                ('address_anchor', models.JSONField(blank=True, null=True)),
                ('signature_offset_x', models.FloatField(default=0)),
                ('signature_offset_y', models.FloatField(default=0)),
                ('signature_page', models.CharField(choices=[('first', 'First page only'), ('all', 'Every page')], default='first', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configuring', 'Configuring'), ('ready', 'Ready'), ('sent', 'Sent')], default='draft', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestation_campaigns', to='members.person')),
            ],
            options={
                'verbose_name': 'Attestation campaign',
                'verbose_name_plural': 'Attestation campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttestationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('extracted_name', models.CharField(blank=True, max_length=300)),
                ('extracted_address', models.CharField(blank=True, max_length=300)),
                ('recipients', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('generated_pdf', models.FileField(blank=True, upload_to='attestations/generated/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attestations.attestationcampaign')),
                ('matched_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestation_items', to='members.person')),
            ],
            options={
                'verbose_name': 'Attestation item',
                'verbose_name_plural': 'Attestation items',
                'ordering': ['page_start'],
            },
        ),
    ]
