# Generated by Django 6.0.3 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attestations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestationcampaign",
            name="documents",
            field=models.FileField(blank=True, null=True, upload_to="attestations/"),
        ),
        migrations.AlterField(
            model_name="attestationcampaign",
            name="signature",
            field=models.FileField(blank=True, null=True, upload_to="attestations/"),
        ),
        migrations.RemoveField(
            model_name="attestationcampaign",
            name="split_mode",
        ),
        migrations.RemoveField(
            model_name="attestationcampaign",
            name="split_marker",
        ),
        migrations.AlterField(
            model_name="attestationcampaign",
            name="signature_page",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Page (1-based, within each person's document) to sign.",
            ),
        ),
        migrations.AddField(
            model_name="attestationcampaign",
            name="name_page",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Page number (1-based) on which the first name appears.",
            ),
        ),
        migrations.AddField(
            model_name="attestationcampaign",
            name="page_range_start",
            field=models.PositiveIntegerField(
                default=1,
                help_text="First page (1-based) of one person's document.",
            ),
        ),
        migrations.AddField(
            model_name="attestationcampaign",
            name="page_range_end",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Last page (1-based) of one person's document.",
            ),
        ),
        migrations.AddField(
            model_name="attestationcampaign",
            name="step",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
