# Generated by Django 6.0.3 on 2026-09-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0002_wizard_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('sent', 'Sent')], default='draft', max_length=15),
        ),
    ]
