# Generated by Django 6.0.8 on 2026-09-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0003_alter_attestationcampaign_status'),
        ('members', '0020_deregistration_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationitem',
            name='match_score',
            field=models.FloatField(blank=True, help_text='How close the extracted name was, 0..1 (suggestions only).', null=True),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='suggested_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestation_suggestions', to='members.person'),
        ),
        migrations.AddField(
            model_name='attestationitem',
            name='suggestion_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
