# Generated by Django 6.0.8 on 2026-09-26 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0004_attestationitem_match_score_and_more'),
        ('members', '0020_deregistration_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationitem',
            name='matched_by_alias',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name as the PDF spells it.', max_length=300)),
                ('match_key', models.CharField(editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestation_name_aliases_created', to='members.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestation_name_aliases', to='members.person')),
            ],
            options={
                'verbose_name': 'Name correspondence',
                'verbose_name_plural': 'Name correspondences',
                'ordering': ['name'],
            },
        ),
    ]
