# Generated by Django 5.2 on 2026-03-29 15:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_fee', models.DecimalField(decimal_places=2, help_text='Cotisation pleine (enfant aîné)', max_digits=8)),
                ('sibling_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Réduction pour fratrie (montant déduit par frère/sœur supplémentaire)', max_digits=8)),
                ('animateur_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cotisation forfaitaire pour animateurs/staff', max_digits=8)),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pénalité de retard en pourcentage (ex: 10.00 pour 10%)', max_digits=5)),
                ('late_deadline', models.DateField(blank=True, help_text='Date limite avant pénalité de retard', null=True)),
                ('school_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_config', to='members.schoolyear')),
            ],
            options={
                'verbose_name': 'Configuration de cotisation',
                'verbose_name_plural': 'Configurations de cotisations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.person')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to='members.person')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.schoolyear')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
    ]
