# Generated by Django 6.0.3 on 2026-07-23 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisationconfig',
            options={'verbose_name': 'Fee configuration', 'verbose_name_plural': 'Fee configurations'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='cotisationconfig',
            name='animateur_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat fee for animators/staff', max_digits=8),
        ),
        migrations.AlterField(
            model_name='cotisationconfig',
            name='full_fee',
            field=models.DecimalField(decimal_places=2, help_text='Full fee (eldest child)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='cotisationconfig',
            name='late_deadline',
            field=models.DateField(blank=True, help_text='Deadline before the late penalty applies', null=True),
        ),
        migrations.AlterField(
            model_name='cotisationconfig',
            name='late_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late penalty as a percentage (e.g. 10.00 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotisationconfig',
            name='sibling_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sibling discount (amount deducted per additional brother/sister)', max_digits=8),
        ),
    ]
