# Generated by Django 6.0.3 on 2026-08-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feerule_and_slim_cotisationconfig'),
        ('members', '0019_email_template_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerule',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all branches', null=True, on_delete=django.db.models.deletion.CASCADE, to='members.branch'),
        ),
    ]
