# Generated by Django 6.0.8 on 2026-09-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_feerule_branch'),
        ('members', '0030_branch_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name the treasurer recognises, e.g. “Famille Dupont”', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative writes off, positive adds to what is owed', max_digits=8)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_household_adjustments', to='members.person')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.household')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_adjustments', to='members.schoolyear')),
            ],
            options={
                'verbose_name': 'Household adjustment',
                'verbose_name_plural': 'Household adjustments',
                'ordering': ['school_year__start_date', 'household__name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='finance.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='members.person')),
            ],
            options={
                'verbose_name': 'Household member',
                'verbose_name_plural': 'Household members',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='households', through='finance.HouseholdMember', to='members.person'),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(fields=('person',), name='uniq_household_per_person'),
        ),
    ]
