# Generated by Django 5.2 on 2025-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_static_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Scouts de Limal', max_length=100)),
                ('site_description', models.TextField(default="Site officiel des scouts de Limal, présentant notre unité et permettant d'inscrire les enfants.")),
                ('site_keywords', models.CharField(default='scouts limal wavre brabant-wallon wallonie belgique baden-powel', max_length=255)),
                ('contact_email', models.EmailField(default='info@scouts-limal.be', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('email_signature', models.TextField(default="Salutations cordiales,\nLe staff d'unité")),
                ('registration_open', models.BooleanField(default=True)),
                ('registration_message', models.TextField(default="Les inscriptions sont ouvertes pour l'année scoute.")),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
