# Generated by Django 6.0.3 on 2026-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_sitesettings"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="parentchild",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="personrole",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "section", "school_year"), name="uniq_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="parentchild",
            constraint=models.UniqueConstraint(
                fields=("parent", "child"), name="uniq_parent_child"
            ),
        ),
        migrations.AddConstraint(
            model_name="personrole",
            constraint=models.UniqueConstraint(
                fields=("person", "role"), name="uniq_person_role"
            ),
        ),
    ]
