# Generated by Django 5.2 on 2026-03-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='next_section',
            field=models.ForeignKey(blank=True, help_text="Override manuel pour le passage : section assignée l'année suivante", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_persons', to='members.section'),
        ),
    ]
