# Generated by Django 5.2 on 2026-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_add_next_section_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='archived_date',
            field=models.DateField(blank=True, help_text='Date à laquelle le membre a été archivé', null=True),
        ),
    ]
