# Generated by Django 5.2 on 2026-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_important_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='secret_key',
            field=models.CharField(blank=True, help_text="Premiers 6 caractères de l'UUID — clé pour lier un parent à un enfant", max_length=6),
        ),
    ]
