# Generated by Django 5.2 on 2026-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_backfill_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_placeholder',
            field=models.CharField(default="Ex: Rue de l'Église 1, 1000 Bruxelles", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_consent_text',
            field=models.TextField(default="J'accepte que les photos ou vidéos soient utilisées par Les Scouts ASBL, dont mon unité fait partie"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@scouts.be', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default="Site officiel de votre unité scoute, permettant d'inscrire les enfants et de gérer les membres."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_keywords',
            field=models.CharField(default='scouts belgique baden-powel', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Scouts', max_length=100),
        ),
    ]
