# Generated by Django 6.0.3 on 2026-07-23 17:03

import django.contrib.postgres.fields
import members.models
from django.db import migrations, models


# (table, [translated base columns]) — copy the existing (French) value of each
# base column into its new default-language (_fr) column so existing data is not
# lost to the AddField default. nl/en stay NULL and fall back to fr at runtime.
TRANSLATED_BASE_FIELDS = {
    "members_role": ["name", "description"],
    "members_branch": ["name"],
    "members_section": ["name"],
    "members_importantdocument": ["title"],
    "members_sitesettings": [
        "site_name",
        "site_description",
        "site_keywords",
        "email_signature",
        "registration_message",
        "photo_consent_text",
        "address_placeholder",
    ],
}


def copy_base_to_fr(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for table, fields in TRANSLATED_BASE_FIELDS.items():
            assignments = ", ".join(f'"{field}_fr" = "{field}"' for field in fields)
            cursor.execute(f'UPDATE "{table}" SET {assignments}')


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_sitesettings_last_passage_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('en', 'English')], default='fr', help_text='Language used for outgoing emails to this user.', max_length=5),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_fr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_nl',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantdocument',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_nl',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_fr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_nl',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_placeholder_en',
            field=models.CharField(default="Ex: Rue de l'Église 1, 1000 Bruxelles", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_placeholder_fr',
            field=models.CharField(default="Ex: Rue de l'Église 1, 1000 Bruxelles", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_placeholder_nl',
            field=models.CharField(default="Ex: Rue de l'Église 1, 1000 Bruxelles", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='available_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('en', 'English')], max_length=5), default=members.models.default_available_languages, help_text='Languages available to users in the site language selector.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_signature_en',
            field=models.TextField(default="Salutations cordiales,\nLe staff d'unité", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_signature_fr',
            field=models.TextField(default="Salutations cordiales,\nLe staff d'unité", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_signature_nl',
            field=models.TextField(default="Salutations cordiales,\nLe staff d'unité", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_consent_text_en',
            field=models.TextField(default="J'accepte que les photos ou vidéos soient utilisées par Les Scouts ASBL, dont mon unité fait partie", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_consent_text_fr',
            field=models.TextField(default="J'accepte que les photos ou vidéos soient utilisées par Les Scouts ASBL, dont mon unité fait partie", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo_consent_text_nl',
            field=models.TextField(default="J'accepte que les photos ou vidéos soient utilisées par Les Scouts ASBL, dont mon unité fait partie", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_message_en',
            field=models.TextField(default="Les inscriptions sont ouvertes pour l'année scoute.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_message_fr',
            field=models.TextField(default="Les inscriptions sont ouvertes pour l'année scoute.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_message_nl',
            field=models.TextField(default="Les inscriptions sont ouvertes pour l'année scoute.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_en',
            field=models.TextField(default="Site officiel de votre unité scoute, permettant d'inscrire les enfants et de gérer les membres.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_fr',
            field=models.TextField(default="Site officiel de votre unité scoute, permettant d'inscrire les enfants et de gérer les membres.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_nl',
            field=models.TextField(default="Site officiel de votre unité scoute, permettant d'inscrire les enfants et de gérer les membres.", null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords_en',
            field=models.CharField(default='scouts belgique baden-powel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords_fr',
            field=models.CharField(default='scouts belgique baden-powel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords_nl',
            field=models.CharField(default='scouts belgique baden-powel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Scouts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_fr',
            field=models.CharField(default='Scouts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_nl',
            field=models.CharField(default='Scouts', max_length=100, null=True),
        ),
        migrations.RunPython(copy_base_to_fr, migrations.RunPython.noop),
    ]
