# Generated by Django 6.0.3 on 2026-07-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_i18n_translation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Important document', 'verbose_name_plural': 'Important documents'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='max_age_dec_31',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age of the oldest members of the section on December 31 of the school year', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='min_age_dec_31',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age of the youngest members of the section on December 31 of the school year', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='archived_date',
            field=models.DateField(blank=True, help_text='Date on which the member was archived', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='next_section',
            field=models.ForeignKey(blank=True, help_text='Manual override for passage: section assigned the following year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_persons', to='members.section'),
        ),
        migrations.AlterField(
            model_name='person',
            name='secret_key',
            field=models.CharField(blank=True, help_text='First 6 characters of the UUID — key to link a parent to a child', max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Boy'), ('F', 'Girl')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='last_passage_school_year',
            field=models.IntegerField(blank=True, help_text='Last school year (the « name » field) for which the automatic passage was executed. Anti-replay: if Celery was stopped on the passage day, the task catches up at the next startup.', null=True),
        ),
    ]
