# Generated by Django 6.0.3 on 2026-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_translate_db_content_nl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('en', 'English')], default='fr', help_text='Default language for visitors. Must be one of the available languages.', max_length=5),
        ),
    ]
