# Generated by Django 6.0.8 on 2026-09-26 14:47

import django.core.validators
import members.models
import members.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_rename_sitesettings_to_troopsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='troopsettings',
            options={'verbose_name': 'Troop Settings', 'verbose_name_plural': 'Troop Settings'},
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='age_reference_day',
            field=models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='age_reference_month',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='archive_retention_years',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='currency',
            field=models.CharField(default='EUR', help_text='Three-letter currency code used to display amounts, e.g. EUR.', max_length=3, validators=[members.models.validate_currency]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='federation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='fees_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='passage_day',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='passage_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', help_text='Automatic runs the passage on the date above; manual leaves it to whoever presses the button.', max_length=10),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='passage_month',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='phone_region',
            field=models.CharField(default='BE', help_text='Country code used to parse and format phone numbers, e.g. BE.', max_length=2, validators=[members.models.validate_phone_region]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Link or text of your privacy policy. A URL becomes a link, anything else is shown as text.'),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='public_agenda_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='reply_to_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='short_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='signing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='year_start_day',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='year_start_month',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=members.phone.TroopPhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
