# Generated by Django 6.0.8 on 2026-09-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_create_default_troop_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_top',
            field=models.BooleanField(default=False, help_text='The last branch of the ladder: members who outgrow it leave it for good.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='promotes_to',
            field=models.ForeignKey(blank=True, help_text='The branch members move into when they outgrow this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='members.branch'),
        ),
        migrations.AddField(
            model_name='person',
            name='passage_review',
            field=models.CharField(blank=True, choices=[('no_section', 'No section fits — choose one'), ('no_next_branch', 'The branch has no next branch set'), ('graduation', 'Leaving the last branch — decide what comes next')], default='', help_text='Set by the passage when it cannot place a member on its own; cleared as soon as one is placed.', max_length=20),
        ),
        migrations.AddField(
            model_name='troopsettings',
            name='top_branch_graduates_become_leaders',
            field=models.BooleanField(default=True, help_text='Members who leave the last branch become animators. Turn this off to be asked about each of them instead.'),
        ),
    ]
