# Generated by Django 6.0.8 on 2026-09-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_branch_key'),
        ('messaging', '0004_messageattachment_sectionmessage_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='troopsettings',
            old_name='public_agenda_enabled',
            new_name='agenda_enabled',
        ),
        migrations.CreateModel(
            name='SectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('reunion', 'Meeting'), ('journee', 'Special day'), ('weekend', 'Week-end')], default='reunion', max_length=10, verbose_name='Activity type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty for an activity that lasts a single day.', null=True, verbose_name='End date')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event', to='messaging.sectionmessage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_events', to='members.section', verbose_name='Section')),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='agenda_event_ends_after_start')],
            },
        ),
    ]
