# Generated by Django 6.0.8 on 2026-09-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_section_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='members.person', verbose_name='Child')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='members.sectionevent', verbose_name='Activity')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_absences', to='members.person', verbose_name='Reported by')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'child'), name='uniq_absence_event_child')],
            },
        ),
    ]
