# Generated by Django 6.0.8 on 2026-09-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_seed_absence_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='Identifier this member has in another system, used to match them when importing.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='uniq_person_external_id'),
        ),
    ]
