"""The single column format the member import and the member export share.

One definition, read by both directions: the key, the header each language
shows for it, and the pair of functions that write its value and read it back.
The writer and the reader of a column sit next to each other on purpose — an
export this module cannot read back is a bug, and keeping the two halves of a
convention far apart is how that happens.

**Headers are translated, values are not.** A header is what a person reads, so
it is written in the language the page is being used in and recognised in every
language the application ships: a file exported in Dutch imports into a site
running in French. A value is what a machine interprets and what a round trip
has to reproduce exactly, so ``M`` stays ``M`` and ``yes`` stays ``yes``
whatever language the file around them is written in. The internal key itself —
``external_id`` — is accepted as a header too, so a file generated by a script
needs no translation table to be readable.

The header index is built from :data:`members.models.AVAILABLE_LANGUAGE_CHOICES`
rather than from the troop's enabled languages: a troop that drops Dutch from
its site still has a Dutch file from last year to import.
"""

import datetime
import re
import unicodedata
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation

from django.utils import translation
from django.utils.translation import gettext, gettext_noop

from members.models import AVAILABLE_LANGUAGE_CHOICES

#: How several values are packed into one cell — role codes, external ids.
#: A semicolon rather than a comma because a comma is what a person writing a
#: section or a household name into the same row is most likely to reach for.
LIST_SEPARATOR = ";"

#: What a boolean column holds. Deliberately not translated, for the reason in
#: the module docstring: a round trip has to reproduce the value, not the word.
YES = "yes"
NO = "no"
_BOOLEAN_WORDS = {
    "yes": True,
    "no": False,
    "true": True,
    "false": False,
    "1": True,
    "0": False,
    "oui": True,
    "non": False,
    "ja": True,
    "nee": False,
}

#: What a ``status`` column holds — the ``Person.status`` short codes.
STATUS_CODES = {"a": "a", "ar": "ar", "r": "r"}
_STATUS_WORDS = {
    "a": "a",
    "ar": "ar",
    "r": "r",
    "active": "a",
    "archived": "ar",
    "requested": "r",
}

#: The two values a ``sex`` column holds — the ``Person.Sex`` short codes.
SEX_CODES = ("M", "F")

# The name/identifier limits the model columns enforce. Checked while planning
# so an over-long value is a row the staff can fix, not a 500 from the database
# halfway through applying the file.
NAME_MAX_LENGTH = 150
ADDRESS_MAX_LENGTH = 200

_ISO_DATE = re.compile(r"^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$")
_DAY_FIRST_DATE = re.compile(r"^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$")


@dataclass(frozen=True)
class Column:
    """One column of the format.

    ``kind`` is what the import page's legend explains the column with — the
    accepted values of a ``sex`` column differ from those of a ``date`` one —
    and it is also what the XLSX writer uses to decide whether a cell is a real
    date or a string.

    ``export_only`` marks a column the export adds and the import ignores: the
    balances, which are a read-out of the fees module and not something a file
    can set.
    """

    key: str
    label: str
    kind: str = "text"
    export_only: bool = False

    def heading(self):
        """The header the active language writes for this column.

        Also what an error message names the column with, so a row complaint
        reads in the language of the person reading it.
        """
        return gettext(self.label)


#: The one row per person both directions agree on.
MEMBER_COLUMNS = (
    Column("external_id", gettext_noop("External ID")),
    Column("first_name", gettext_noop("First name")),
    Column("last_name", gettext_noop("Last name")),
    Column("birthdate", gettext_noop("Date of birth"), kind="date"),
    Column("sex", gettext_noop("Sex"), kind="sex"),
    Column("email", gettext_noop("Email")),
    Column("phone", gettext_noop("Phone")),
    Column("address", gettext_noop("Address")),
    Column("primary_role", gettext_noop("Primary role"), kind="role"),
    Column("secondary_roles", gettext_noop("Secondary roles"), kind="roles"),
    Column("parent_external_ids", gettext_noop("Parent external IDs"), kind="list"),
    Column("section_current_year", gettext_noop("Section this year"), kind="section"),
    Column("section_next_year", gettext_noop("Section next year"), kind="section"),
    Column("household", gettext_noop("Household")),
    Column("photo_consent", gettext_noop("Photos allowed"), kind="bool"),
    Column("notes", gettext_noop("Notes")),
    # Not in the list the format was specified with, and added deliberately:
    # an export that cannot say "this member is archived" cannot be re-imported
    # without resurrecting them, and re-importing an export is the whole point.
    Column("status", gettext_noop("Status"), kind="status"),
)

#: Appended by the export when the fees module is on. Read-only: the import
#: accepts them in a file (it just ignores them) so that exporting, editing
#: something else, and importing back does not need the columns deleted first.
BALANCE_COLUMNS = (
    Column("amount_due", gettext_noop("Due"), kind="amount", export_only=True),
    Column("amount_paid", gettext_noop("Paid"), kind="amount", export_only=True),
    Column("balance", gettext_noop("Balance"), kind="amount", export_only=True),
)

#: The second file: one row per recorded payment. Exported and imported only
#: while the fees module is on.
PAYMENT_COLUMNS = (
    Column("external_id", gettext_noop("External ID")),
    Column("school_year", gettext_noop("School year"), kind="year"),
    Column("amount", gettext_noop("Amount"), kind="amount"),
    Column("date", gettext_noop("Date"), kind="date"),
    Column("note", gettext_noop("Note")),
)


def column_for(key, columns=None):
    """The column a key names, from either of the two tables.

    The keys are unique across both, so one lookup answers for a member row and
    a payment row alike — which is what lets an error message name a column it
    only knows the key of.
    """
    for column in (
        MEMBER_COLUMNS + BALANCE_COLUMNS + PAYMENT_COLUMNS
        if columns is None
        else columns
    ):
        if column.key == key:
            return column
    return Column(key, key)


def member_columns(include_balances=False):
    """The member columns, with the balances the export adds when fees are on."""
    if include_balances:
        return MEMBER_COLUMNS + BALANCE_COLUMNS
    return MEMBER_COLUMNS


# --- Headers ----------------------------------------------------------------


def fold_header(text):
    """Fold a header down to what makes two of them the same column.

    Case, accents, a stray byte-order mark and a run of spaces all vary between
    the spreadsheet a header was typed into and the one it comes back from, and
    none of them changes which column it names. Folding them away is what lets
    ``Prénom``, ``Prenom`` and ``prénom`` be one header.
    """
    stripped = unicodedata.normalize("NFKD", str(text or ""))
    ascii_only = stripped.encode("ascii", "ignore").decode("ascii")
    return " ".join(ascii_only.casefold().split())


def header_index(columns=None):
    """``{folded header: internal key}`` across every shipped language.

    The internal key is in the index too, so a file written by a script that
    names its columns ``external_id`` and ``first_name`` imports unchanged.
    """
    index = {}
    for column in MEMBER_COLUMNS if columns is None else columns:
        index.setdefault(fold_header(column.key), column.key)
        for code, _name in AVAILABLE_LANGUAGE_CHOICES:
            with translation.override(code):
                heading = column.heading()
            # setdefault, not assignment: the first language to claim a header
            # keeps it, so a header two languages spell alike is stable.
            index.setdefault(fold_header(heading), column.key)
    return index


# --- Values -----------------------------------------------------------------


def parse_date(value):
    """A ``datetime.date`` from a cell, or ``ValueError``.

    Accepts an ISO date, the day-first one a European spreadsheet writes, and
    the date objects both the XLSX reader and a hand-built row can carry.
    """
    if value is None or value == "":
        return None
    if isinstance(value, datetime.datetime):
        return value.date()
    if isinstance(value, datetime.date):
        return value
    text = str(value).strip()
    for pattern, order in ((_ISO_DATE, "ymd"), (_DAY_FIRST_DATE, "dmy")):
        match = pattern.match(text)
        if match is None:
            continue
        parts = [int(part) for part in match.groups()]
        year, month, day = parts if order == "ymd" else reversed(parts)
        try:
            return datetime.date(year, month, day)
        except ValueError:
            break
    raise ValueError(gettext("Expected a date, e.g. 2020-05-04 or 04/05/2020."))


def format_date(value):
    """A date as this format writes it: ISO, and nothing else."""
    return value.isoformat() if value else ""


def parse_sex(value):
    """One of the ``Person.Sex`` codes, or ``ValueError``."""
    text = str(value or "").strip().upper()
    if not text:
        return None
    if text in SEX_CODES:
        return text
    raise ValueError(gettext("Expected M or F."))


def format_sex(value):
    return value or ""


def parse_bool(value):
    """A boolean cell, or ``ValueError``; an empty cell is ``None``.

    ``None`` rather than ``False`` so a row that says nothing about photo
    consent leaves the stored value alone instead of clearing it.
    """
    if value is None or value == "":
        return None
    if isinstance(value, bool):
        return value
    text = str(value).strip().casefold()
    if text in _BOOLEAN_WORDS:
        return _BOOLEAN_WORDS[text]
    raise ValueError(gettext("Expected yes or no."))


def format_bool(value):
    return YES if value else NO


def parse_status(value):
    """A ``Person.status`` code, or ``ValueError``; empty is ``None``."""
    text = str(value or "").strip().casefold()
    if not text:
        return None
    if text in _STATUS_WORDS:
        return _STATUS_WORDS[text]
    raise ValueError(gettext("Expected one of: a, ar, r."))


def format_status(value):
    return STATUS_CODES.get(value, value or "")


def parse_list(value):
    """The items of a ``;``-separated cell, trimmed and without empties."""
    if value is None or value == "":
        return []
    return [item.strip() for item in str(value).split(LIST_SEPARATOR) if item.strip()]


def format_list(values):
    return LIST_SEPARATOR.join(values)


def split_section_ref(value, branch_keys):
    """A section cell as ``(branch key or None, section name)``.

    Two spellings are accepted, because a section name alone is ambiguous as
    soon as a troop has two sections called ``1`` under different branches: the
    bare name, and ``key:name`` where ``key`` is the ``Branch.key`` of the
    preset the branch came from.

    The colon is only a separator when what precedes it really is a branch key,
    so a section whose own name contains a colon still resolves by its name.
    """
    text = str(value or "").strip()
    if not text:
        return None, ""
    prefix, separator, rest = text.partition(":")
    if separator and prefix.strip() in branch_keys:
        return prefix.strip(), rest.strip()
    return None, text


def format_section_ref(name, branch_key, ambiguous):
    """How the export writes a section: the name, or ``key:name`` when needed.

    A name two sections share cannot be read back on its own, so the branch key
    goes in front of it — which is exactly the case the format's second
    spelling exists for. A branch with no key (one no preset created) has
    nothing to qualify with, so the bare name goes out and the import warns.
    """
    if not name:
        return ""
    if ambiguous and branch_key:
        return f"{branch_key}:{name}"
    return name


def parse_decimal(value):
    """A ``Decimal`` from a cell, or ``ValueError``.

    Accepts the English decimal point and the European decimal comma, including
    a number that carries both and a thousands separator (``1.234,56`` and
    ``1,234.56`` both read as 1234.56): whichever separator comes last is the
    decimal one.
    """
    if value is None or value == "":
        return None
    if isinstance(value, Decimal):
        return value
    if isinstance(value, (int, float)):
        return Decimal(str(value))
    # A non-breaking or narrow space is what a spreadsheet puts into a
    # number it decided was text, and what a paste off a web page carries.
    text = re.sub(r"[\s\u00a0\u202f]", "", str(value))
    if not text:
        return None
    if "," in text and "." in text:
        decimal_separator = "," if text.rindex(",") > text.rindex(".") else "."
        text = text.replace("." if decimal_separator == "," else ",", "")
        text = text.replace(decimal_separator, ".")
    elif "," in text:
        text = text.replace(",", ".")
    try:
        return Decimal(text)
    except InvalidOperation:
        raise ValueError(gettext("Expected a number, e.g. 12.50.")) from None


def format_decimal(value):
    """A money amount as this format writes it — a plain point decimal."""
    if value is None:
        return ""
    return f"{value:.2f}"


def to_cell(value, column):
    """The cell text a stored value is written as, for one column."""
    if column.kind == "date":
        return format_date(value)
    if column.kind == "amount":
        return format_decimal(value)
    if column.kind == "bool":
        return format_bool(value)
    if column.kind == "status":
        return format_status(value)
    if column.kind == "list" or column.kind == "roles":
        return format_list(value or [])
    return "" if value is None else str(value)
