#SPDX-License-Identifier: MIT-0
---
# tasks file for troopconnect
- name: permanently enable https service, also enable it immediately if possible
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true
  become: true

- name: permanently enable http service, also enable it immediately if possible
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
  become: true

- name: Replace the email address in Candyfile
  ansible.builtin.replace:
    path: caddy/Candyfile
    regexp: '^\s*email\s+\S+'
    replace: "email {{ letsencrypt_contact_email }}"
  become: true
