#SPDX-License-Identifier: MIT-0
---
# tasks file for troopconnect
- name: permanently enable https service, also enable it immediately if possible
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true
  become: true

- name: permanently enable http service, also enable it immediately if possible
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
  become: true
