# Generated by Django 5.2 on 2026-03-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_enrollment_unique_together_and_more'),
        ('messaging', '0002_section_message_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmessage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='members.section'),
        ),
    ]
