# Generated by Django 6.0.3 on 2026-08-16 12:18

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homepage_images/%Y/', validators=[homepage.models.validate_image_extension])),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image asset',
                'verbose_name_plural': 'Image assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('faq', 'FAQ')], max_length=20, unique=True)),
                ('project_json', models.TextField(blank=True, null=True)),
                ('project_json_fr', models.TextField(blank=True, null=True)),
                ('project_json_nl', models.TextField(blank=True, null=True)),
                ('project_json_en', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('html_fr', models.TextField(blank=True, null=True)),
                ('html_nl', models.TextField(blank=True, null=True)),
                ('html_en', models.TextField(blank=True, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('css_fr', models.TextField(blank=True, null=True)),
                ('css_nl', models.TextField(blank=True, null=True)),
                ('css_en', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site contents',
            },
        ),
    ]
