#SPDX-License-Identifier: MIT-0
---
# tasks file for infra
- name: Add Docker repository
  ansible.builtin.command: >
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Install git and docker and prepare for certbot (EPEL)
  ansible.builtin.package:
    name:
      - git
      - docker-ce
      - docker-compose-plugin
      - epel-release
    state: present
  become: true
- name: Install certbot
  ansible.builtin.package:
    name:
      - certbot
    state: present
  become: true

- name: Enable and start docker
  ansible.builtin.systemd_service:
    state: started
    name: docker
    enabled: true
  become: true

- name: Create Docker network "shared_net" if it doesn't exist
  community.docker.docker_network:
    name: shared_net
    state: present
    driver: bridge

- name: Enable and start firewall
  ansible.builtin.systemd_service:
    state: started
    name: firewalld
    enabled: true
  become: true

- name: Git pull or clone
  ansible.builtin.git:
    repo: "https://github.com/tdebruyn/TroopConnect.git"
    dest: "{{ project_dir }}"
    version: main
    force: yes
  become: true

- name: Copy local deploy/ansible/config.yml to remote {project_dir}/deploy/ansible/config.yml
  ansible.builtin.copy:
    src: config.yml
    dest: "{{ project_dir }}/deploy/ansible/config.yml"
  become: true

- name: Allow SSH service in the firewall
  ansible.posix.firewalld:
    port: "{{ ssh_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  become: true
