# Generated by Django 4.1.7 on 2023-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='group_name',
            field=models.CharField(default='changeme', max_length=150, verbose_name='nom'),
        ),
    ]
