# Generated by Django 4.1.7 on 2023-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_customgroup_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_consent',
            field=models.BooleanField(default=False, help_text='I give my consent to use my photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='Required only for childrens', null=True),
        ),
    ]
