# Generated by Django 4.1.7 on 2023-03-30 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_historicalcustomuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('start_age', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.customgroup'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
