# Generated by Django 4.1.7 on 2023-03-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_age_alter_customgroup_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='range',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
