# Generated by Django 4.1.7 on 2023-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_customuser_photo_consent_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'groupe', 'verbose_name_plural': 'groupes'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='customgroup',
            name='adult',
            field=models.BooleanField(default=False, help_text='This group is users who can create an account'),
        ),
    ]
