# Generated by Django 4.1.7 on 2023-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_customuser_address_customuser_phone_customuser_sex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='base',
        ),
    ]
