# Generated by Django 4.1.7 on 2023-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_customuser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
